ioos/compliance-checker

README.md
In `.condarc` file for Windows installation content description, multiple test binstar channels replaced with the single official IOOS channel.
This is the update of the just merged request #78.
=> Update the binstar channels

compliance_checker/acdd.py, compliance_checker/cf/util.py, requirements.txt
This PR replaces `udunitspy` with `cf_units`, making it possible to run compliance-checker on Windows.  The PR passes `python2 setup.py test`, but more tests are probably needed before merging.
The implementation here followed that of `udunitspy`, but with some optimizations made possible by the `cf_units` API.  
Unfortunately the file diff shows extra changes ("diff noise") due to leading blank spaces that I can fix if necessary. 
Closes #61 (and maybe #62).  It does not depend on swig which will make #65 easier.
(Also closes https://github.com/ioos/conda-recipes/issues/225.)
=> Using cf_units instead of udunitspy.

compliance_checker/acdd.py, compliance_checker/cf/util.py, requirements.txt
This PR replaces udunitspy with cf_units, making it possible to run compliance-checker on Windows. The PR passes python2 setup.py test, but more tests are probably needed before merging.
The implementation here followed that of udunitspy, but with some optimizations made possible by the cf_units API.
Unfortunately the file diff shows extra changes ("diff noise") due to leading blank spaces that I can fix if necessary.
Closes #61 (and maybe #62). It does not depend on swig which will make #65 easier.
(Also closes ioos/conda-recipes#225)
=> Using cf_units instead of udunitspy

compliance_checker/acdd.py, requirements.txt
- Petulant Bear still had the unicode issues if they are present in
datasets, this commit sets the version explicitly to the (now) newest
release.
- ACDD had a few bugs in it where the messages in the Results objects
were strings instead of lists or iterables, which resulted in an
exception being raised later.
- Basically, if you were checking ACDD, some test failures would result
in checker crashing.
=> Fixes ACDD Checks and adds explicit ver of pb

compliance_checker/cf/cf.py
@DanielJMaher please pull/review.  @lukecampbell please review/merge.
=> Allow non-dtype vars in CF check_units, fixes #144

compliance_checker/cf/cf.py
The list of strings dual_role should be lower case since we're trying to compare it against ```getattr(ds.dataset, 'featureType', '').lower()```.
At the moment this check is giving false result for the following featureType : timeSeriesProfile, trajectoryProfile.
=> test on featureType value should be case insensitive

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Brings CF `check_value_outside_valid_range` in line with other checks.
```
fill_value                             :3:    47/48 :  
PROFILE                            :3:     0/ 1 :  
outside_valid_range            :3:     0/ 1 : 99999 must not be between
0 and 900000
```
instead of a single flat result with `(47/48)` and many messages (that weren't working properly anyway).
=> Update CF check fill value to modern style, fixes #147

compliance_checker/cf/cf.py, compliance_checker/cf/util.py, compliance_checker/tests/test_cf.py
If the file *units* attribute of a time variable contains a string that cannot be parsed by cf_units, the CF  `check_time_coordinate` method throws an exception, which is reported at the beginning of the output like this:
```
The following exceptions occured during the cf checker (possibly indicate compliance checker issues):
cf.check_time_coordinate: [UT_SYNTAX] Failed to parse unit "days since 1950-01-01 T00:00:00Z" 
```
This PR adds a unittest to test for this case, and fixes it by catching the exception in the `units_temporal` util method.
While I was at it, I also added a couple of tweaks to the reasoning messages returned by `check_time_coordinate` (see individual commit messages). Hope these make sense.
=> Handle an exception in CF check_time_coordinate

.travis.yml, requirements.txt
- `sudo: false` moves from the old travis to the new and faster travis
- `conda update --yes --all` updates everything rather than just conda
- `cf_units==0.1.1` This is the real fix.  The previous version had a baked conda numpy string for NP19 and the rest of the packages were compiled against numpy > 1.10.0.
=> Fix travis

compliance_checker/cf/cf.py
This check was failing if the non-space-time dimension was on the far right.  In python the space-time variables are the leftmost and then the non-space-time the right most.  Flipped it so we check properly now.
=> Fixes #200 . check_dimensional_order

compliance_checker/cf/cf.py
Remove the list of conventions allowed.  Keeps the logic that supports multiple conventions as it does not harm and we might want to leverage it later.
=> Closes #86 . Reverts back to only accept CF 1.6

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Updates messages for `flag_values` attribute where attribute type is not
the same as the values in contained within the parent variable to
include the variable name.
Fixes #192.
=> Update `flag_values` type mismatch message

README.md
This reflects the code I needed to write to use compliance-checker from Python.
=> Fixed 'Usage (from Python code)' section

compliance_checker/base.py, compliance_checker/tests/test_suite.py
The value of a Result object is expected to be either of type `tuple` or `bool`, but there is nothing enforcing this. While this is true most of the time, in the IMOS check suite we've created some Results having a value of type `numpy.bool_` (e.g. the result of `numpy.all()`). This didn't cause a problem earlier, but since da674bcc5dcc5745394e7dea1eafd9b5a376a54c it breaks because `_translate_value()` (in suite.py) returns such a value unchanged, while its output is expected to always be a tuple.
I've added a unittest to demonstrate this issue, and suggested a change to the `Result` object to ensure that the `value` attribute is always one of the expected types.
=> Force Results.value to be bool or 2-tuple

compliance_checker/base.py, compliance_checker/tests/test_suite.py
Comment in the definition of the `Result` object (in base.py) suggest a value of `None` can be used to signify a skipped test. I missed this in #270. Here is an update to allow for that, if it is deemed relevant.
=> Allow Result.value = None

requirements.txt
This was an omission after removing Wicken, which depended on it.
=> Add netCDF4 to requirements

compliance_checker/suite.py
The checker is running fine in my (Linux) terminal, but when I try to redirect the output to a file, this happens:
```
$ compliance-checker -t=cf file.nc >/tmp/cc.out
Running Compliance Checker on the dataset from: file.nc
Traceback (most recent call last):
File "/sw/anaconda/envs/cc/bin/compliance-checker", line 9, in <module>
load_entry_point('compliance-checker', 'console_scripts', 'compliance-checker')()
File "/sw/chef/src/compliance-checker/cchecker.py", line 56, in main
args.format)
File "/sw/chef/src/compliance-checker/compliance_checker/runner.py", line 44, in run_checker
groups = cls.stdout_output(cs, score_groups, verbose, limit)
File "/sw/chef/src/compliance-checker/compliance_checker/runner.py", line 74, in stdout_output
cs.non_verbose_output_generation(score_list, groups, …
```
=> Avoid UnicodeEncodeError when checker output is redirected

cchecker.py
- -t or --test was a nargs parameter, now it's a append parameter so you
can add test choices with multiple -t flags in the CLI. This seems
more UNIX-like. Also it fixes some reported issues about people can't
run it with:
compliance-checker -t acdd mydataset.nc
- Tests will now not be choice but can be listed as part of a new CLI
argument -l or --list-tests
=> Changes the argument parsing in the CLI

compliance_checker/cf/cf.py
- cf_role doesn't have to be just timeseries_id, it can be profile_id
etc.
- This just removes variables that define cf_role from the potential of
being identified as geophysical_variables
=> Makes the variable detection more hardened

cchecker.py
Since we now have check suites from plug-ins that have their own code version (the `_cc_checker_version` attribute), independent of the core checker code, the user may want to see what versions are in use.
Here I've added the code version to the output from the `--list-tests` command-line argument. Alternatively, it could be added to the `--version` output.
=> Add code version when listing check suites

compliance_checker/tests/test_cf.py
@lukecampbell removes the test for alternative coordinates as described here https://github.com/ioos/compliance-checker/issues/289
=> Remove check alternative coordinates

cchecker.py, compliance_checker/cf/cf.py, compliance_checker/cf/util.py, compliance_checker/tests/test_cf.py
@lukecampbell @daf @kwilcox Can one of you guys review please?
This PR addresses https://github.com/ioos/compliance-checker/issues/247.
During the CF test, if a file has a particular version of the cf standard name table specified in the global attributes (i.e. ```:standard_name_vocabulary = "CF Standard Name Table v30" ;```) that doesn't match the packaged version, it will try to download the specified version. If it fails, it will fall back to packaged version.
This PR also adds ability to update the packaged version by using the 'd' switch and passing in the version you want to fetch.
```
python cchecker.py -d 34
```
=> Dynamically download specified cf standard name table

compliance_checker/runner.py, compliance_checker/suite.py, compliance_checker/tests/test_cli.py
Allows 'text' format to be output to file with the `-o` option, i.e.
`compliance-checker -t acdd -f text -o cc_results.txt ncfile.nc`
Fixes #290.
=> Allows output of text to file

compliance_checker/acdd.py
According to CF-1.6, coordinate variables shouldn't have a _FillValue
attribute. But since acdd.check_vertical_extents() uses _FillValue, it
was not possible to check for ACDD while complying with CF-1.6.
=> BUGFIX #319, coordinate variables shouldn't have _FillValue.

compliance_checker/runner.py, compliance_checker/suite.py, compliance_checker/tests/test_cli.py, test_requirements.txt
* Changed the CheckSuite's `json_output` to a `dict_output`, making it much more useful for future output formats (when that gets revamped).
* Multiple score groups now work with the `json` output format
* Cleaned up tests (there was a duplicate test name)
* Added a test that examines `stdout` contents. This should be mimicked as needed in other output formats to test the contents of `stdout` (its not tested at all right now).
=> Fixes json output when using multiple score groups

compliance_checker/cf/cf.py
Fixes a boolean logic error which would return the opposite result of
what was desired upon checking if there were any zero values in
flag_masks attribute. Fixes #316.
=> Fixes boolean logic error in flag checks

compliance_checker/base.py, compliance_checker/cf/cf.py, compliance_checker/cf/util.py, compliance_checker/cfutil.py, compliance_checker/tests/__init__.py, compliance_checker/tests/data/bad_units.cdl, compliance_checker/tests/data/rotated_pole_grid.cdl, compliance_checker/tests/resources.py, compliance_checker/tests/test_acdd.py, compliance_checker/tests/test_cf.py, compliance_checker/tests/test_feature_detection.py
- Replaces `_find_data_vars` with `_find_geophysical_variables`
- Refactors `check_units` to correctly validate units according to section 3 of CF 1.6
- Splits the complicated logic of `check_units` into three functions
- Adds more detailed unit tests to check assertions of failure and success
=> Refactor check_units

compliance_checker/cf/cf.py, compliance_checker/cfutil.py, compliance_checker/tests/test_cf.py
- Refactor check_standard_name
- Change the set of variables being checked
- If a variable defines long_name standard_name check is optional
- Include standard name table in version
- Check standard_name modifiers
- Adds get_flag_variables to cfutil
=> Refactors check_standard_name

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
CF §2.3 
> ... it is _recommended_ that names should not be distinguished purely by case
I changed the priority to medium, since the language uses "recommended," and not "suggest" or "optional".
=> Adds test for duplicate variable names

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
- Scalar coordinates are now being checked just like all the other
coordinates and they are inherently associated with variables through
the `coordinates` attribute.
=> Removes deprecated check on scalar coordinates

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
- Updates label in test
My assumption up until this point was that coordinate types where
physical data representing a coordinate of the variable. This is
supported in every chapter right up until chapter 6. §6.1, Labels,
throws a huge wrench into this assumption.
Chapter 6 allows for auxiliary coordinates to be labels, like regions or
station names or whatever. It was my assumption, until I reread it, that
labels just shared dimensions with features, not were directly related
through coordinates.
I personally disagree with this, labels aren't conceptually coordinates
they would be better suited as ancillary data. They don't define where,
or when in the physical world or a mapped coordinate system.
In any case this refactor corrects my incorrect assumption.
=> Fixes assumption about coordinates

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
- Chapter 4 mainly applies to gridded features.
- There is no requirement for non-spatial coordinates to have
units/axis/standard_name
- There is no requirement for an axis to have an explicit relationship
to a spatial coordinate in chapter 4.
=> Fixes chapter 4 assumptions

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Implements section 8.2 of the CF manual, "Compression by
gathering"/issue #394 on GitHub.
Checks that compression variable containing compress attribute has
exactly one dimension, the compression variable is of integer type, and
the referenced dimensions from the blank-separated 'compress' attribute
exist within the NetCDF dataset.
=> Implements 8.2, "Compression by gathering"

compliance_checker/cf/cf.py, compliance_checker/tests/data/grid-boundaries.cdl, compliance_checker/tests/test_cf.py
Skips dimension order checks for climatology and cell bounds variables.  Still
checks the parent variables, but it is unnecessary to check the former
variables as they already have their own set of checks which make the
generalized dimensional checks somewhat redundant.  Additionally, the
generalized checks were leading to erroneous bad results.  Should
address #325.
=> Skips coordinate order checks for climatology and cell bounds variables

compliance_checker/tests/test_cf_integration.py
- Making a strict test that depends on the order of dict.items()
produces random failures.
=> Fixes random test failures

compliance_checker/cf/cf.py, compliance_checker/cfutil.py, compliance_checker/tests/test_cf_integration.py
- Skip attribute checks on attributes beginning with DODS or _ChunkSize
- Geophysical variables can NEVER be strings
=> Changes some behavior

compliance_checker/base.py, compliance_checker/cf/cf.py
Updates docstrings to allow API documentation generation for the CF
checker.  Also removes a few unused methods in `cf.py`.  Implements #336.
=> Updates CF checker docstrings for Sphinx

.travis.yml, compliance_checker/cf/cf.py, test_requirements.txt
@lukecampbell it seems that @jbosch-noaa cannot use `np.float128` on some Windows machines.
This PR changes the logic to check if `scale_factor` is the primitive `float` or `np.floating` (which means any of those in the list there.)
PS: I incorporated #479 so we can run the tests.
=> Check for float without relying on np.float128

.travis.yml, test_requirements.txt
The `master` branch is failing at the moment due to the pinning. 
```
Traceback:
compliance_checker/tests/test_cf_integration.py:4: in <module>
from compliance_checker.suite import CheckSuite
compliance_checker/suite.py:15: in <module>
from lxml import etree as ET
E   ImportError: libicui18n.so.58: cannot open shared object file: No such file or directory
```
Full log: https://travis-ci.org/ioos/compliance-checker/jobs/197774152#L514
Hopefully this will fix https://github.com/ioos/compliance-checker/issues/451 too.
=> Investigate Travis-CI failures

.travis.yml, compliance_checker/tests/test_ioos.py, requirements.txt, test_requirements.txt
`httpretty` is not Python 3 compliant and the packages in `defaults` should be used with care (`conda-forge`) does not package them BTW. (See https://github.com/gabrielfalcao/HTTPretty#disclaimer)
However the problem was being masked because the tests where running on Python 2.7 only due to a weird bug: the presence of `python-datetutil` in the requirements list. (Check the previous logs and [this](https://travis-ci.org/ocefpaf/compliance-checker/builds/220922447) without `python-datetutil`.)
So this PR removes `python-datetutil`, to enable Python 3 tests, and works around the lack of `httpretty` in `test_ioos.py`.
=> Remove python-dateutil and workaround httpretty

README.md, appveyor.yml, compliance_checker/cf/util.py, compliance_checker/tests/test_cli.py, compliance_checker/tests/test_suite.py, conda.recipe/meta.yaml
In this PR:
- build the `conda-recipe` on Windows as a packaging test;
- enable Windows testing to avoid regression like #480;
- properly close files in the test framework to make them pass on  Windows.
Note that I enabled Windows test using my own account. Different from Travis-CI, where the members have access to the configuration and that is tied to the repo, with AppVeyor the configuration is tied to the user :unamused: 
Someone inside IOOS should take charge of that to avoid problems in the future.
=> Windows tests

.travis.yml, compliance_checker/protocols/cdl.py, compliance_checker/protocols/netcdf.py, compliance_checker/protocols/opendap.py, compliance_checker/suite.py, compliance_checker/tests/test_ioos.py, compliance_checker/tests/test_protocols.py, conda.recipe/meta.yaml
We recently found out that Hyrax and ERDDAP did not work because the
server intitally returns a HTTP 200/Content-type: text/html when an HTTP
request is made to a DODS endpoint. This is so user's don't see the
error page that THREDDS shows when a user visits a pure DODS endpoint.
We relied on this behavior of THREDDS and the too literal interpretation
of DAPv2's specification to identify services implementing OPeNDAP.
This patch includes better identification of services implementing
OPeNDAP, and SOS. As well as a faster check for binary datasets like
netCDF.
Identification now works by checking if 'xdods-server' exists in the
response headers. In the case for SOS, if the response headers has
'text/xml' in the content-type header, then it is treated as an SOS
response.
Binary netCDF files …
=> Adds better support for detecting dataset protocol

README.md
After refactoring the dataset loader, we no longer support reading local
XML files. And to read CDL files, the files must be named to end with a
`.cdl`
=> Updates README with clarifications

compliance_checker/cf/util.py, compliance_checker/tests/test_cf.py
@lukecampbell I am putting https://github.com/ioos/compliance-checker/pull/482/commits/e38d3962571c3c9661309644d17d09a8c37171cb#r110988217 in from of a PR.
I added a test that passes a non-existent table file to `StandardNameTable`. That should fail b/c there is no such file but it does not raise the expected `IOError` and `compliance-checker`, silently, uses a default table instead. Users relying on that API may be getting the wrong table version without knowing. Because `StandardNameTable` is part of the public API I believe that we should change that behavior and fail gracefully. My next commit will change the code with that suggestion.
=> Add a test that should fail

compliance_checker/cf/cf.py
The original fix in #496 could result an error if no variables have cell_measures attributes as it's trying to reference `valid` and `var` before they exist when it's creating the Result at the bottom.  It also wouldn't allow more than one variable with `cell_measures` if that happened to be the case.
This mostly reverts the changes in #496, but fixes the original problem of dealing with what `get_variables_by_attributes` returned.  Tests are passing locally for me.
=> Fixup branching logic in cell_measures, fixes #495

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py, compliance_checker/tests/test_cf_integration.py
The checker checks the Conventions global attribute but only allows
'CF-1.6' currently. This patch improves the reasoning message indicating
that the checker can only check CF-1.6 at the moment.
https://github.com/ioos/compliance-checker/issues/501
=> Adds better reasoning statement for Conventions check

README.md
The given instructions print out nothing with the latest code since it overwrites `skip_checks` and `output_filename`
=> Update instruction for usage from Python code.

compliance_checker/cf/cf.py
Uses `ancillary_variable in ds.variables` instead of
`ancillary_variables in ds.variables`.  Fixes #464.
=> Use proper variable name for ancillary var check

compliance_checker/cf/cf.py, compliance_checker/tests/data/bad_cf_role.cdl, compliance_checker/tests/resources.py, compliance_checker/tests/test_cf_integration.py
The cf_role checks was returning an empty set without any actual checks.
This patch fixes the check for cf_role and addresses #491.
=> Fixes cf_role checks

.travis.yml
conda-forge dropped support for `Python 3.4` and we are testing against `Python 3.5` and `3.6`, so it is safe to drop it from here too.
=> Drop Python 3.4 tests

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Improve checking of cell methods contents which appear inside parentheses.  Currently these include standalone comments (no colon), interval specifications, and comments coming after standard elements.  Also checks if the element with a colon even exists and throws an error if it does not.
=> Cell methods improvements

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Puts an error message where neither standard_name nor long_name in
section 3.2 instead of section 3.3.  Refactors checker logic and
rewrites unit tests.  Addresses #506.
=> Change error message, refactor logic for long/standard name detection

compliance_checker/cf/cf.py
The way it was written, I was getting the following when running the tests.
```
compliance_checker/tests/test_cli.py::TestCLI::test_text_output WARNING: The following exceptions occured during the cf checker (possibly indicate compliance checker issues):
cf.check_cf_role: local variable 'valid_cf_role' referenced before assignment
```
=> Fix bug in check_cf_role

.travis.yml
This may sound like an overkill but all the new plugin tests are set to "`allow_failures`", so they won't be a noise in the main tests.
By testing all the latest plugin code downstream we can catch failures early and/or have a tool to find what change in `compliance-checker` broken the plugin.
=> Test downstream plugins

compliance_checker/data/templates/ccheck.html.j2, compliance_checker/data/templates/ccheck_wrapper.html.j2, compliance_checker/runner.py, compliance_checker/suite.py
Previously only the last test to run would be shown in the HTML output. In fact, the results for each test would be written to the same output file sequentially, overwriting the results of the previous test.
For example, after running `checker.py -o output.html -f html --test cf --test acdd <dataset>`, `output.html` would only show results for the `acdd` test.
This change splits the HTML template into two files
* one with the header bar, CSS etc
* one to show the results of a single test
The second template is rendered for each test and included in the first.
=> Support showing output from multiple tests in HTML output

README.md, cchecker.py
Multiple arguments were accepted for `dataset_location`, but the
checker was only actually run on the first one.
=> Fix running checks on multiple datasets

cchecker.py
This makes the list of tests much more tidy. 
```
$ python cchecker.py -l
IOOS compliance checker available checker suites:
- acdd:1.1
- acdd:1.3
- cf:1.6
- ioos:0.1
- ioos:1.1
- ioos_sos:0.1
```
Verbose option:
```
$ python cchecker.py -l -v
IOOS compliance checker available checker suites:
- acdd (v3.1.1)
- acdd:1.1 (v3.1.1)
- acdd:1.3 (v3.1.1)
- acdd:latest (v3.1.1)
- cf (v3.1.1)
- cf:1.6 (v3.1.1)
- cf:latest (v3.1.1)
- ioos (v3.1.1)
- ioos:0.1 (v3.1.1)
- ioos:1.1 (v3.1.1)
- ioos:latest (v3.1.1)
- ioos_sos (v3.1.1)
- ioos_sos:0.1 (v3.1.1)
- ioos_sos:latest (v3.1.1)
```
=> Cleanup the list of available tests

appveyor.yml, compliance_checker/acdd.py, compliance_checker/data/templates/ccheck.html.j2, compliance_checker/runner.py, compliance_checker/suite.py, compliance_checker/tests/test_suite.py
@benjwadams this is going into the refactor-scoring branch. This PR simply removes the scoring section of the output (html and standard output, json is unchanged) as a starting point. What's left is the reasoning section that is now divided into the high, medium and low priorities.
=> Remove scoring section from html and standard output

compliance_checker/suite.py
Fixes an issue with version selection when no version or ":latest" was
specified.  Also uses distutils.versions.StrictVersion for comparing
version numbers to determine latest and falls back on comparing via strings
if the version can't be parsed.
=> Fixes version select issue with latest

compliance_checker/acdd.py, compliance_checker/base.py, compliance_checker/cf/cf.py, compliance_checker/ioos.py, compliance_checker/runner.py, compliance_checker/suite.py, compliance_checker/tests/test_suite.py
To prevent staleness and allow 3rd party plugins to override priority names, a new class attribute (`_cc_display_headers`) is introduced mapping priority names to display strings.  If not defined in the derived checker, the base ones are used.
- create _cc_display_headers attr in each Checker
- make checker name a required positional argument where used
Will need to be done in the NCEI suite of checkers too (I can do this if no one else can get to it, but tell me).
=> Move Suite.get_priority_headers into Checker based class attributes

compliance_checker/cfutil.py, compliance_checker/tests/test_feature_detection.py
This proposed solution fixes the problem I reported in #562 for that particular test files. The change makes sense to me because I don't really understand the logic behind the lines that I've removed. However, there may be a good reason to keep them! I'm just putting this up for discussion and review.
This broke one unittest:
compliance_checker/tests/test_feature_detection.py::TestFeatureDetection::test_global_feature_detection
I have updated this test so that it now passes.
=> Fix #562 duplicate axis coordinates

compliance_checker/cf/cf.py, compliance_checker/tests/data/dimension_order.cdl, compliance_checker/tests/resources.py, compliance_checker/tests/test_cf.py
Fixes #535, at least for the specific example I encountered.
I have simplified the regular expression used to check the dimension order, so this might change the return value of this check for other data sets. However, based on [CF section 2.4](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#dimensions), which this check is implementing, I don't see why there is a need for a more complicated regex than what I have put here.
In particular, I don't see why the previous version allows dimensions other than "X" at the end of the list of dimensions?
=> Fix CF dimension order check

.gitignore, compliance_checker/cf/cf.py, requirements.txt
This fixes the `FutureWarning` we are from latest `numpy`
```
compliance_checker/tests/test_cf.py::TestCF::test_check_flag_masks
/home/travis/build/ocefpaf/compliance-checker/compliance_checker/cf/cf.py:1351: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
type_ok = (np.issubdtype(variable.dtype, int) or
```
=> from int to np.signedinteger is deprecated

requirements.txt
This will use the latest `cftime`, which was bundled in `netcdf4` as `netcdftime` before. In theory there should be no code breakages in `compliance-checker`.
PS: it would be nice to get a new micro point release so people can get udpated `netcdf4` packages on their systems.
=> use cf_units 2.0

compliance_checker/cf/cf.py, compliance_checker/cfutil.py
Uses set types for membership tests against possible names of various
coordinates.  This will possibly speed the code up a little bit since
set membership is an `O(1)` operation instead of `O(n)` for lists.
=> Uses set instead of list types for CF coord var tests

compliance_checker/cf/cf.py, compliance_checker/cfutil.py, compliance_checker/tests/test_cf_integration.py
In order for the CF Integration Tests to pass, they needed some updating. Many test methods had assertion phrasing that needed to be reworded to match the current check version. Instead of hard-coding the std. names table version into the assertions, the code now gets it for us (this was one of the most common failures).
One failure case I am unsure how to approach is in `test_glcfs`, l. 252, where as assertion states that the boundary variable `eta` does not exist in the dataset. While this is true, the message is never generated by the CF check because the dataset has no variables with the `bounds` attribute, and thus does not test the variables referenced in the `formula_terms` attribute. Any guidance on this would be appreciated (maybe you know something, @benjwadams?).
References …
=> CF Integration Tests Fixes

compliance_checker/cf/cf.py, compliance_checker/cfutil.py, compliance_checker/tests/test_cf.py
Renames a number of functions and variables related to checks for units
when standard_name is determined to be dimensionless.  Also expands the
accepted UDUnits dimensionless units names checked.
=> Updates names, check for dimensionless standard names

cchecker.py
This does not technically "fix" #607, as there are still ways to call that method and get the UnboundLocalError esp when using CC programatically, but this makes it behave like a command line tool is expected to.
=> Show help when no operations are requested on the command line, updates #607

README.md, cchecker.py, compliance_checker/runner.py, compliance_checker/suite.py, compliance_checker/tests/test_suite.py
Allows skipping of specific priority levels from within checks by using
a modified form of `<skip_check>:<max_level>`.  Max level can be one of
"A", "M", or "L", which correspond to skipping all output (same as
default invocation with `<skip_check>`), skipping medium and low priority
items within the check, and skipping only low priority checks,
respectively.  Implements #589.
=> Allows skipping specific levels of individual checks

compliance_checker/protocols/opendap.py
Latest `netcdf-c` broke a lot of our datasets due to https://github.com/Unidata/netcdf-c/issues/1299. For now we have a workaround by adding `#fillmismatch` to the end of the URL endpoint, but that breaks `compliance-checker`'s `is_opendap`.
This PR adds a support for the URL with the workaround.
=> support url fillmismatch workaround

compliance_checker/data/templates/ccheck.html.j2
To go along with the updated grouping process, the HTML output now looks like
compared to the old result:
=> HTML updates to go along with new grouping methods

compliance_checker/data/templates/ccheck_wrapper.html.j2
Clicking directly on icon was not working, only click on text would hide/show.
@Bobfrat @daltonkell
=> Fix issue with report icon dropdown click not working

compliance_checker/acdd.py, compliance_checker/cf/cf.py, compliance_checker/tests/helpers.py, compliance_checker/tests/test_acdd.py
Addresses a few quick issues related to comparing data values to metadata, message improvements.
acdd.py:
- check_lat_extents(), check_lon_extents(), and _check_total_z_extents() -- all tried to compare
data values to metadata values, which may have been passed as strings. numpy copmarision would
subsequently fail; fixed by casting the potential string values as floats (Issue #639)
- check_coverage_content_type() was outputting the string "coverage_content" instead of
"coverage_content_type"; inserted the correct string (Issue #637)
cf.py:
- _check_formula_terms() was outputting a message about missing variables, but did not include
the variables it was referring to. Fixed by adding a format field. (Issue #636)
- check_grid_coordinates() message was a little ambiguous -- added some …
=> Quick Improvements 2019-04-11

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Per issue #468, some special attributes defined in the NetCDF User Guide (NUG)
had data types which did not match their parent variable. E.g.
float temperature(time);
temperature:standard_name = "air_temperature";
temperature:units = "deg_C";
temperature:valid_range = -20, 50; # --> integers, not floats
Currently, type-mismatches for these special attributes are checked in
"check_packed_data()" for only variables which are packed. This commit
adds a new check which examines each variable. If the variable has one
of these special attributes and a type-mismatch exists, it is scored.
This commit also adds unit tests for the new check.
It is worth noting that, while "actual_range", "actual_min", and
"actual_max" are not defined in the CF-1.6 spec, this check includes
them for easier …
=> Verifying Special-Attribute Data Types

compliance_checker/tests/data/ncei_gold_point_1.cdl
Fixes cell_methods attributes in variables which had references to
nonexistent variables "longitude" and "latitude". Replaced these with
"lon" and "lat" respectively.
=> Fixes cell_methods on "gold standard" point metadata

compliance_checker/acdd.py, compliance_checker/tests/helpers.py, compliance_checker/tests/test_acdd.py
Adds unit tests for geospatial vertical min/max.  Also handles case
where all Z axis array is empty or all values are masked by raising a
failure case, as the min/max cannot be established from an empty input
array.
=> Handle vertical min/max, including zero length arrays

compliance_checker/cf/cf.py, compliance_checker/cfutil.py, compliance_checker/tests/test_cf.py
This started out as a fix to a small bug, but also includes two other minor tweaks:
* ba051b7 is the bug fix - `check_duplicate_axis` was failing incorrectly when the name of one variable was  a substring of another (e.g. if a dataset has both "DEPTH" and "NOMINAL_DEPTH" with axis='Z', and "TEMP" defined only "NOMINAL_DEPTH" as an auxiliary coordinate variable, `get_axis_map` would still pick up both depth vars, leading to an apparent duplicate Z axis).
* 4aaa5b6 is a suggestion - I assume if a varaible actually has an axis attribute defined in a meaningful way, there's no need for `get_axis_map` to try and guess what the axis is??
* ba051b7 is also a suggestion - I think this makes the error message more helpful.
I hope this makes sense. Feel free to reject either of the last two …
=> Small fix & update to CF check_duplicate_axes

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Handles bad and unparseable CF standard name table versions by raising a
warning and returning `False` inside `_find_cf_standard_name_table`
=> Handle bad CF standard name table versions

compliance_checker/acdd.py, compliance_checker/base.py, compliance_checker/tests/test_acdd.py
@benjwadams this addresses https://github.com/ioos/compliance-checker/issues/654
Previously the error message did not tell the user which attribute was checked or what the incorrect value was, making it difficult to fix the issue. This PR adds the attribute name and the erroneous value in the error message.
=> Add better error message for the geospatial bounds check

cchecker.py, compliance_checker/suite.py, compliance_checker/tests/test_cli.py
Allows checkers using the `.name` attribute instead of the `._cc_spec` and
`cc_spec_version` to be listed in the checker output.  Checkers using
the former will raise a `DeprecationWarning` indicating the checker is
not preferred.  Also refactors some of the check suite logic for
printing listings and adds unit test for aforementioned behavior.
Addresses #610.
=> Allows checkers using .name attr to be listed

README.md, cchecker.py, compliance_checker/suite.py
Adds `-D`/`--describe-checks` feature to compliance checker.  This PR represents a squashed, rebased version of the previous draft PR listed in #661, which @daf provided feedback upon.
=> Describe checks

compliance_checker/base.py, compliance_checker/cf/cf.py, compliance_checker/tests/test_base.py
Adds a new method to `compliance_checker.base.BaseCheck` called
`get_test_ctx`, which attempts to fetch a `TestCtx` from a defaultdict
specific to the checker instance.  If the check does not exist, it is
created in the dict, otherwise, the corresponding dict entry is returned
for further modifications.  Allows predefined `TestCtx` objects to be
reused across functions so that the same `TestCtx` doesn't have to be
passed around one monolithic function.  Potentially also useful for
extending checking behavior defined in newer checker versions, i.e.
additions to check behavior between CF versions.
=> Adds a new method `get_test_ctx` to reuse `TestCtx`

compliance_checker/base.py, compliance_checker/cf/cf.py, compliance_checker/cfutil.py, compliance_checker/suite.py, compliance_checker/tests/helpers.py, compliance_checker/tests/test_base.py, compliance_checker/tests/test_cf.py, requirements.txt
Adds functionality to check grid mapping attributes for `geoid_name` and `geopotential_datum_name`.
Also overhauls return type for `check_grid_mapping` in both CF 1.6 and 1.7 to use `collections.OrderedDict` instead of `list` so that the 1.7 check can add to the results of the common behavior of the check between 1.6 and 1.7.   This mechanism works with stdout output, but if the raw results are being used by any other programs, the behavior may need to be modified, as iterator over `OrderedDict` will return keys instead of values.  PR is marked as draft as of the time of this writing to allow for discussion about pros/cons and possible other mechanisms for extending checks between different versions of the same checker parent class.
=> Verify OGC Vert datum name

compliance_checker/cf/cf.py
A THREDDS Server might add global attributes starting with EXTRA_DIMENSION as documented by unidata:
https://www.unidata.ucar.edu/software/netcdf-java/current/CDM/Opendap.html
These global attributes should be ignored by the compliance checker.
=> ignore global attr starting with EXTRA_DIMENSION

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
TracTicket #76: More Than One Name in "Conventions"
Implement backwards-compatible check for CF-1.6 where the Conventions
attribute is only permitted to contain one name. In CF-1.7, multiple names
are allowed. Remove the inherited method from the BaseCheck, as that
implementation does not belong there.
=> Multi string conventions

compliance_checker/cf/cf.py
Twice replaced `grid_mapping_dict` by `grid_mapping` in function
check_grid_mapping. `grid_mapping` is one element of in
`grid_mapping_dict`. In the two situations, the particular grid mapping
and not the whole dictionary of all grid mappings was to use.
=> minor fix in check_grid_mapping; fixes #682

compliance_checker/tests/test_cf.py
_FillValue must be set at variable creation. Facilitate this by
completely removing the MockTimeSeries from memory, creating it anew,
then creating the variable again with the desired _FillValue.
=> Fix test failure for _FillValue creation

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
This commit addresses issue #688.
The actual_range check implementation was inconsistent with the specification.
Ensure that the actual_range is checked to fall within the bounds of the valid_range,
valid_min, and valid_max. Remove actual_min and actual_max from "special_attrs",
as these are not defined in the specification.
=> Fix actual range check

compliance_checker/cf/cf.py
Two error/warning messages, which each consiste of more than one line
of text output, were missing a space between two split lines.
=> add spaces to user messages in check_grid_mapping

compliance_checker/cf/__init__.py, compliance_checker/cf/appendix_d.py, compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Issue summary: Some vertical coordinates are functions of other variables,
thereby defining a need to describe the appropriate method to compute their
exact values. The computed_standard_name maps to the parameterized vertical
coordinate.
Enable the checking of the computed_standard_name attribute from Appendix D
in CF-1.7 while maintaining compatiblity with CF-1.6. Add the appropriate values
to the Appendix and corresponding unit tests.
=> Trac Ticket #143: Computed Standard Name

compliance_checker/cf/cf.py
Modified the checking of the number of variables with specific
attributes required by a grid mapping. Previously `==1` was checked (are
variable with a specific required standard name was allowed to exist
only once). Now, `>=1` is checked (the variable has to exist at least
once). The user output was updated accordingly.
=> mod. check of req. vars with std.name for grid map; fixed #691

compliance_checker/cf/cf.py, compliance_checker/suite.py, compliance_checker/tests/test_cf.py
Adds a check for CF 1.6 and 1.7 attributes, as well as a general
framework to execute these checks.
Practically the same as #690, recreating to see if AppVeyor failures can  be prevented.
=> Check Appendix A attributes for CF 1.6 and 1.7

requirements.txt
OWSLib was recently updated. In order to not break the build, constrain the version.
=> Use OWSLib < 0.19.0 for Python 2 support

compliance_checker/cf/cf.py
If 'unidentifiable feature for variable' arose in the past, it was not
penalized meaning that no individual error was thrown. However, this led
to the issue that the message did not appear in the output of compliance
checker if no other error/warning/information was printed out for
section 9.1. Now, it is regularly penalized and a message appears every
time.
=> penalize 'unidentifiable feature for variable'; fixed #679

compliance_checker/cf/cf.py, compliance_checker/tests/data/grid_mapping_coordinates.cdl, compliance_checker/tests/resources.py, compliance_checker/tests/test_cf.py
Verifies that grid mapping coordinate variables that exist as part of a grid_mapping attribute are well formed and exist as variables within the dataset.  Implements https://cf-trac.llnl.gov/trac/ticket/70.
=> Verify grid mapping coordinate vars under CF 1.7

.appveyor.yml
Should address failures in #705
=> Removes Python 2.7 from AppVeyor test matrix due to failures

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Updates messages emitted by Appendix A attribute to include human
readable type of variable in addition to the corresponding letter code
from the Appendix A "Use" column.
=> Update Appendix A attribute location warnings

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Corrects code which finds coordinate data variables to include both NUG
coordinate variables (variables with one dimension where the name of the
dimension and variable are the same) and existing variables in the
dataset which are referred to by other variables' "coordinates"
attribute.
=> Correct coordinate data variable finding code

README.md, cchecker.py, compliance_checker/base.py, compliance_checker/cf/cf.py, compliance_checker/runner.py, compliance_checker/suite.py, compliance_checker/tests/test_cf.py
Adds an `--option`/`-O` flag to the CLI which can pass along additional behavior to individual checkers.
Commits in this PR also disable the CF Appendix A checks by default, but allow them to by turned on by passing `cf:enable_appendix_a_checks` to the aforementioned options.
=> Add option flag to CLI

.travis.yml, requirements.txt
Support for Python 2.7 is no longer needed. References #726 .
=> Remove support for Python 2.7 in .travis.yml and requirements.txt

compliance_checker/base.py, compliance_checker/tests/test_base.py
Fixes tests IOOS validators for email by using `validators.email` for
stricter checking.   Also fixes a unit test for mulitple URL checking
when CSV splitting of the input text field was specified by adding a
missing comma to the appended test string.
=> Fix IOOS validator tests

compliance_checker/ioos.py, compliance_checker/tests/helpers.py, compliance_checker/tests/test_ioos_profile.py
Checks the following:
- `gts_ingest` (global and variable)
- `contributor_role` and `contributor_role_vocabulary`
- geospatial (coordinate) variables as well as geophysical variables
- explicit check for `platform` global attribute
- explicit check for `platform` variable attribute, with routine to examine shape of dimension variables
- ensure both geophysical and geospatial variables meet respective requirements
Commit 34f5c02 enables users to supply a default `_FillValue` while constructing a `MockTimeSeries`. This can make testing the `FillValue` possible for coordinate variables, e.g. `time`. I am open to cherry-picking this commit into its own feature branch if that's desired.
=> Added features for IOOS Metadata Profile v1.2

compliance_checker/suite.py, compliance_checker/tests/data/test_cdl_nc4_file.cdl, compliance_checker/tests/test_suite.py
* generate netCDF4 file from cdl with ncgen: When a CDL file is provided, currently, a netCDF classic file is created by ncgen. However, a CDL file might contain netCDF4 features such as attributes/variables of type int64 (indicated by `LL` after numbers). Therefore, the `ncgen`-call that creates a netCDF file was modified to create a netCDF4 instead of a netCDF-classic file. If this does not work, we try to create a netCDF Classic file. If that does not work, we exit the program.
* added cdl file with netcdf4 features for testing
* two new test for netCDF4 file generation
=> generate netCDF4 file from cdl file by default and corresponding tests

compliance_checker/ioos.py
The `gts_ingest` check accidentally prints out the `netCDF4` string representation of the variables it's looking at instead of the name:
```
Highly Recommended                               
--------------------------------------------------------------------------------
gts_ingest variable
* The attribute "gts_ingest" of variable "<class 'netCDF4._netCDF4.Variable'>
float64 s.air_temperature(s)
_ChunkSizes: [240760      1]
_FillValue: -9999.0
actual_range: [ 2.16 34.8 ]
ancillary_variables: air_temperature_qc_agg air_temperature_qc_tests
gts_ingest: true
id: 1000735
ioos_category: Other
long_name: Air Temperature
missing_value: -9999.0
platform: station
standard_name: air_temperature
standard_name_uri: http://mmisw.org/ont/cf/parameter/air_temperature
```
This commit uses the name …
=> Fix variable print-out bug

compliance_checker/acdd.py, requirements.txt
Since cftime release 1.1.0, num2date returns instances of cftime.Datetime.
In order to return datetime objects, use the convenience function
cftime.num2pydate.
=> Change num2date to num2pydate

compliance_checker/ioos.py
Remove redundant messages for `contributor_role`, `contributor_role_vocabulary`, and `ioos_ingest`. Each has an explicit check, so they are not needed in the recommended attributes.
=> Ioos  1 2  redundant msgs

compliance_checker/ioos.py, compliance_checker/tests/test_ioos_profile.py
This addresses #762 quite succinctly, but I'm worried that the error message at 
https://github.com/ioos/compliance-checker/blob/54b5300663b70e586ca429e2ecdad12f0e155314/compliance_checker/base.py#L488
is going to be quite unclear to some users. I'm going to ping for @benjwadams for some insight. The machinery is already here, which makes a pull request this simple so tempting.
=> Ensure platform_id is an alphanumeric string

compliance_checker/ioos.py, compliance_checker/tests/test_ioos_profile.py
Addresses #760 (in part, see bottom of discussion; other parts are being addressed separately). Ensure the `wmo_platform_code` conforms to the specification of
- numeric string of 5 or 7 characters
- alphanumeric strings of 5 characters
This is corresponds with the [specification](https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html#platform) (see "wmo_platform_code" in the table).
=> Ensure wmo_platform_code conforms to specification

compliance_checker/ioos.py, compliance_checker/tests/test_ioos_profile.py
Any value supplied other than "true" or "false" should fail;
add improved error message for clarity.
Now, no more "ioos_ingest" message when testing on https://pae-paha.pacioos.hawaii.edu/erddap/tabledap/WQB-04.html:
```
$ dalton@ubuntu:~/compliance-checker$ python cchecker.py -t ioos:1.2 WQB-04.ncCF | grep "ioos_ingest"
Running Compliance Checker on the datasets from: ['WQB-04.ncCF']
```
```
=> Improve ioos_ingest check

compliance_checker/cf/cf.py, compliance_checker/ioos.py, compliance_checker/tests/test_ioos_profile.py
All QARTOD variables should have flag_meanings and flag_values
attributes. Add checks to look for their existence and test they
meet the requirements put forth in the CF specifications.
New output looks like so (for the [org_cormp_sun2.nc](http://testing.erddap.axds.co/erddap/tabledap/org_cormp_sun2.nc) dataset):
```
qartod_variables flags
* air_temperature_qc_agg's flag_values must be an array of values not <class 'str'>
* air_pressure_qc_agg's flag_values must be an array of values not <class 'str'>
* relative_humidity_qc_agg's flag_values must be an array of values not <class 'str'>
* sea_water_velocity_to_direction_qc_agg's flag_values must be an array of values not <class 'str'>
* sea_water_speed_qc_agg's flag_values must be an array of values not <class 'str'>
* …
```
=> Add check to examine flag_values and flag_meanings

compliance_checker/cfutil.py, compliance_checker/tests/data/forecast_reference.cdl, compliance_checker/tests/resources.py, compliance_checker/tests/test_feature_detection.py
This commit updates cfutil's feature detection to ignore variables used
to declare forecast metadata. Specifically, variables with standard
names `forecast_period` and `forecast_reference_time` are used in
conjunction with `time` to indicate to dataset consumers the appropriate
model initialization time, forecast hour, and valid time. This is
useful for datasets that aggregate multiple forecast runs, such as FMRC.
=> Adds support for forecast reference metadata in CF checks.

compliance_checker/base.py
Some metadata fields like "contributor_email" were not being
populated with messages; fix this to the desired behavior.
Example
Current behavior:
```
Recommended                                   
--------------------------------------------------------------------------------
contributor_email
contributor_name
* contributor_name not present
contributor_role
* contributor_role should be from NERC or GEOIDE
* contributor_role not present
contributor_role_vocabulary
* contributor_role_vocabulary should be one of NERC or GEOIDE
* contributor_role_vocabulary not present
contributor_url
```
Improved behavior:
```
Recommended                                   
--------------------------------------------------------------------------------
contributor_email
* contributor_email not present …
```
=> Fix lack of messages where ValidatorObject is used

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Handles both string and bytes in parent variable check of attribute
types when parent variable is a string type.
Addresses #782
=> Handle both string and bytes in parent variable check

compliance_checker/ioos.py
Two "None" values were being displayed for the gts_ingest failure
message, inidcating a passing check. Ensure no messages are displayed
on a passing check.
Additional testing revealed the need for this adjustment.
=> Ensure gts_ingest_requirements message only displays on failure

compliance_checker/cf/cf.py, compliance_checker/data/templates/ccheck.html.j2
Fixes an issue referenced in https://github.com/ioos/compliance-checker/issues/780 where unescaped HTML would be printed in the HTML format.
Also changes flag_masks error message to be slightly more readable.
=> Fix flag messages HTML output

README.md, cchecker.py, compliance_checker/cf/util.py
Adds an option to the `-d` flag to download the latest CF standard name
table without needing to explicitly specify a version.  This is expected
to be useful in cases with non-interactive runs () of the compliance
checker (e.g. scheduled checker runs) where an up to date standard name
table is desired.
Supersedes #793 and eliminates the need for BeautifulSoup4 library.
=> Adds ability to fetch latest CF standard name table

.github/workflows/pre-commit.yml, .gitignore, .isort.cfg, .pre-commit-config.yaml, test_requirements.txt
Once merge this will add a GitHub action that runs the pre-commit hooks configuration.
The checks are:
https://github.com/pre-commit/pre-commit-hooks
- trailing space
- check-ast
- debug-statements
https://github.com/pre-commit/mirrors-isort
https://github.com/asottile/seed-isort-config
- isort with third party from seed-isort
https://github.com/psf/black
- black
https://github.com/pre-commit/mirrors-mypy
- mypy
I use all of those in my projects but we may not need of them at once here.
Fixing all code style checks cab be done incrementally or in a single massive commit. While the latter is harder I'd rather do it once and then we just need to keep the code tidy. Also, a massive commit makes git-blame easier thanks to git >=2.23 `--ignore-revs`', see …
=> add pre-commit hooks

compliance_checker/__init__.py, compliance_checker/protocols/erddap.py, compliance_checker/protocols/netcdf.py, compliance_checker/protocols/opendap.py, compliance_checker/suite.py, compliance_checker/tests/test_protocols.py
Take elements of #799 and #800 to fetch remote NetCDF resources and uses this capability to fetch ERDDAP TableDAP datasets with the .ncCF extension.
=> Remote NetCDF TableDAP

compliance_checker/protocols/opendap.py, compliance_checker/suite.py
Checks if TableDAP endpoint has `application/x-netcdf` Content-Type header prior to rewriting URL.  This fixes an issue where specifying a URL such as https://gliders.ioos.us/erddap/tabledap/amelia-20180501T0000.nc?&time%3E=max(time)-3%20hours  would attempt to rewrite and would lead to a dataset that didn't exist.
=> Tabledap check content type

setup.py
It was observed that the setup script reads the requirements file twice.
This commit removes a line that may have been left over from a previous
way of defining the project's requirements, and shifts the
responsibility of reading the project's dependencies to the
`pip_requirements` function.
=> Removes 2x requirements file scan

compliance_checker/ioos.py
Add the HTTPS protocol for the NERC URL. Remove comments
stating that NERC URL is broken (it is fixed).
Addresses #810.
=> Remove comment for broken link, add https protocol

README.md, cchecker.py
Updates help text to reflect added support for remote netCDF
(non-OPeNDAP) and ERDDAP TableDAP endpoints.
=> Updates CLI help text of supported dataset types

compliance_checker/suite.py
I understand that `compliance-checker` does not use that name for anything but the method is public and using the file contents as the name is a bit awkward. Also, the file contents can be a huge string depending on the dataset, maybe this can improve performance a little bit too.
=> use file path instead of contents as name

compliance_checker/data/templates/ccheck.html.j2, compliance_checker/suite.py
Reports (all formats) now include the version of the Compliance Checker
as well as the date the report was run.
=> Add the timestamp of report generation and version

compliance_checker/cf/cf.py
Zero-dimensional data variables cannot have a feature type -- but they might be geophysical variables. Up till now, all variables returned by `self._find_geophysical_vars(ds)` were iterated. This lead to some issues. Some zero-dimensional variables might be geophysical variables. Therefore, they should be returned by `_find_geophysical_vars`. However, they should not be iterated in one for-loop, which throws an error on each not-identifiable feature type (fixes parts of #719 ).
=> ignore zero-dim variables when determining featureType; part of #719

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
fixed #836 
* update message from `VARIBALE's dimensions are not in the recommended order T, Z, Y, X. They are DIMENSIONs` to `VARIBALE's spatio-temporal dimensions are not in the recommended order T, Z, Y, X and/or further dimensions are not located left of T, Z, Y, X.  The dims are DIMENSIONs. Their guessed types are DIMENSION_TYPES (U: other/unknown; L: unlimited).`.
* updated unit test, which checks this warning message
=> improve warning message when dimension order is bad (CF 2.4)

compliance_checker/ioos.py, compliance_checker/tests/test_ioos_profile.py
Addresses issue #828.
Enable any variable, not just platform variables, to have
the cf_role variable. Break out into modular functions and
adjust unit tests accordingly. Squashed messages below.
WIP cf_role issue 128
WIP Make cf_role checking funcs individual funcs
WIP individual func and unit test for timeseries (single, multiple station)
WIP func for featureType=timeseriesprofile, unit test
WIP func for featureType=trajectory
WIP func for featureType=trajectoryprofile, unit test
WIP func for featureType=profile, fix up timeseries
WIP remove old function and unit test
WIP backtrack on some new issue comments
All cf_role vars for timeseries_id, profile, trajectory must
have dimensions of 1.
Add space before period
Remove old CF DSG check and unit test
``` …
```
=> Addresses issue 828

compliance_checker/cf/appendix_f.py, compliance_checker/tests/test_cf.py
* grid mapping false east/north optional; fixes #716: Attributes false_easting and false_northing are now optional for grid mapping variables. Previously, they were mandatory. The `optional` is in agreement with CF-1.8. In CF version prior to 1.8 it was ambiguous whether these attributes were mandatory or not.
* added projections_*_coordinate to new projections
* updated grid mapping test according to changes
=> grid mapping false east/north optional; fixes #716

compliance_checker/cf/cf.py, compliance_checker/tests/test_cf.py
Eliminates a problem where the _FillValue values would be compared
against actual_range values, causing erroneous failures.  Also fixes a
minor scoring bug in case valid_min and/or valid_max are not defined.
=> Don't unmask masked values when running actual_range checks

compliance_checker/cf/cf.py
As mentioned in https://github.com/ioos/compliance-checker/pull/875#discussion_r680690974, if the `featureType` global attribute is missing, the CF check suite throws a `'NoneType' object has no attribute 'lower'` exception.
This should prevent that, without affecting any of the logic.
=> Prevent exception when feature_type attribute missing

compliance_checker/tests/conftest.py, compliance_checker/tests/test_cli.py
This is a pretty incremental change but I figured I should make a separate PR for it rather than mix it with something else. Just updating the test_cli.py tests to use pytest instead of unittest, in the same vein as [PR #880](https://github.com/ioos/compliance-checker/pull/880).
=> Remove unittest dependency for command line tests

README.md
Python 2.7 has stopped being supported long time ago, so a notice that it is no longer supported is fairly superfluous.   PyPI/setup.py should indicate supported versions Python versions in any event.
Many other people have made contributions to compliance checker, so it's recommended that this section be removed.
=> Remove Python 2.7 warning / contributors image added in README

compliance_checker/cf/cf_1_6.py, compliance_checker/tests/test_cf.py
Fixes to flags:
- Checks that 0 does not appear in `flag_masks`
- Fixes `flag_values` checking when attribute is single-valued/scalar (fixes #992)
=> Flag fixes

.pre-commit-config.yaml, compliance_checker/cf/appendix_c.py, compliance_checker/cf/cf_1_6.py, compliance_checker/cf/cf_1_8.py, compliance_checker/cf/util.py
Fixes pre-commit spelling errors reported by `codespell`.  Also adds
"Claus" to the list of excluded words since it is referenced in a
biological data citation of an author for a mocked WoRMS entry.
=> Fixes spelling issues reported by `codespell`

compliance_checker/cfutil.py, compliance_checker/ioos.py
Removes checks for _FillValue and missing_value on coordinate variables
in IOOS profile checker which should not take place per CF Conventions
section 2.5.1.
=> Remove extraneous attribute checks on coordinate variables

compliance_checker/cf/cf_1_6.py
This is in reference to [issue #953](https://github.com/ioos/compliance-checker/issues/953)
Updated the function "check_cell_measures" to include:
=> updated check_cell_measures

compliance_checker/cf/cf_1_6.py
Related to [issue#956] (https://github.com/ioos/compliance-checker/issues/956) Solving:
=> Updated check_compression_gathering

.github/dependabot.yml
@benjwadams we should probably port this to the `develop` branch too.
=> add dependabot to keep the GHA updated

compliance_checker/cf/cf_1_6.py, compliance_checker/tests/test_cf.py
Reverts ioos/compliance-checker#961
=> Revert "Only allow fixed length string variables to be one or two-dimensional"

compliance_checker/cf/cf_1_6.py, compliance_checker/tests/test_cf.py
@mhidas, should address issue mentioned in #986 by using an alternative implementation for excluding _FillValue time data.
=> Fix calendar crossing 1582 issue on some builds

.pre-commit-config.yaml
Excludes seanames.csv and a testing configuration file from codespell pre-commit checking.
=> Exclude miscellaneous files from being checked by codespell

compliance_checker/cf/cf_1_6.py, compliance_checker/cf/cf_1_9.py, compliance_checker/cf/cf_base.py, compliance_checker/tests/helpers.py, compliance_checker/tests/test_cf.py, compliance_checker/tests/test_cf_integration.py
Adds implementations and tests for the following sections:
Required:
- The reference date/time in time units is not allowed to contain seconds equal to or greater than 60.
Recommendations:
- The use of time coordinates in year 0 and reference date/times in year 0 to indicate climatological time is deprecated.
- Units of year and month and any equivalent units should be used with caution.
=> Implement majority of conformance for CF section 4.4

compliance_checker/acdd.py, compliance_checker/cf/cf_1_6.py, compliance_checker/cf/cf_1_7.py, compliance_checker/cf/cf_1_9.py, compliance_checker/cf/cf_base.py, compliance_checker/ioos.py
@benjwadams these changes addresses some of your comment in #1026.
=> minor fixes, left over from #1026

requirements.txt
Some builds were failing on isodate requirements due to newer setuptools not having 2to3 support.  Newer builds of isodate shouldn't have this issue.
=> Pin isodate >= 0.6.1 in requirements.txt

docs/source/conf.py
We should revisit that URL and check if it is back online in the near future. For it is safe to skip so we can get the docs to build again.
=> let's skip this one for now

.pre-commit-config.yaml, cchecker.py, compliance_checker/acdd.py, compliance_checker/base.py, compliance_checker/cf/cf_1_6.py, compliance_checker/cf/cf_1_7.py, compliance_checker/cf/cf_base.py, compliance_checker/cf/util.py, compliance_checker/ioos.py, compliance_checker/runner.py, compliance_checker/suite.py, compliance_checker/tests/cassettes/test_erddap.yaml, compliance_checker/tests/test_acdd.py, compliance_checker/tests/test_cf.py, compliance_checker/tests/test_cf_integration.py, compliance_checker/tests/test_feature_detection.py, compliance_checker/tests/test_protocols.py
Alternative for https://github.com/ioos/compliance-checker/pull/1036
=> Fix pre commits

.pre-commit-config.yaml, compliance_checker/cf/cf_1_6.py, compliance_checker/cf/cf_1_7.py, compliance_checker/cf/util.py, compliance_checker/cfutil.py, compliance_checker/protocols/netcdf.py, compliance_checker/suite.py, compliance_checker/tests/__init__.py, compliance_checker/tests/conftest.py, compliance_checker/tests/resources.py, compliance_checker/tests/test_cf_integration.py, compliance_checker/tests/test_suite.py, pyproject.toml, requirements.txt
[pkg_resources is notoriously slow and problematic](https://github.com/pypa/setuptools/issues/926). This PR tries to remove it from compliance-checker.
=> Remove pkg resources

compliance_checker/base.py, compliance_checker/protocols/netcdf.py, compliance_checker/suite.py, compliance_checker/tests/test_cf.py, compliance_checker/tests/test_cf_integration.py, compliance_checker/tests/test_protocols.py, compliance_checker/tests/test_suite.py, docs/source/development.md, docs/source/faq.md, docs/source/index.rst
* base.py: Sometimes cfutil is None
* protocols/netcdf.py:
- Return False right away if content_type is None
- Support extended type strings: "application/x-netcdf;ver=4"
* suite.py: If text for xml fails, look for netcdf one more time
* Convert suite.run() calls to suite.run_all() calls
* Update hyrax url
* Update thredds url
* Add some development notes for troubleshooting tests with pytest using the vcr feature.
For the SOS test in test_protocols.py, I set that to skip.  I searched for awhile for a working SOS service.
Looking forward to seeing https://github.com/ioos/compliance-checker/pull/1039 merged.
=> Some pytest fixes

.github/workflows/cc-plugin-ncei-test.yml
We thought that https://github.com/ioos/cc-plugin-ncei/issues/52 would break this test here but it turns out we are not testing this plugin. Maybe we don't need it anymore? Do you know why we don't have it here @benjwadams?
Anyway, the NCEI plugin has an upstream test and should pass here as well. Let's try...
=> add NCEI downstream plugin test

README.md, docs/source/conf.py, docs/source/index.rst, docs/source/readme_link.md
This was already the case but we were copying-n-pasting the contents. Now we can edit the README and the quick intro section will be auto-updated.
PS: We need to convert the wiki contentes to docs and update them.
=> Use README.md as quickintro

.github/workflows/cc-plugin-glider-test.yml, .github/workflows/cc-plugin-ncei-test.yml, .github/workflows/cc-plugin-og-test.yml, .github/workflows/cc-plugin-sgrid-test.yml, .github/workflows/cc-plugin-ugrid-test.yml, .github/workflows/deploy-docs.yml
We ended up testing against a release compliance-checker instead of the development version.
=> Conda was clobbering the dev version of compliance-checker

.pre-commit-config.yaml, compliance_checker/base.py, compliance_checker/suite.py
Asserts are dropped when using optimizations or compilers. They should be used only in tests, not in code. For more info see https://docs.astral.sh/ruff/rules/assert/
=> Remove assert statement

compliance_checker/cf/cf_1_6.py, compliance_checker/cf/util.py, compliance_checker/tests/test_cf.py
@benjwadams do you mind taking a look? I'm not sure if that duplication was introduced to avoid a circular import or something similar. If not, I'd like to simplify this as I work on #1094.
=> Remove duplicated function

.github/workflows/default-tests.yml, .pre-commit-config.yaml, compliance_checker/cf/cf_1_6.py, compliance_checker/cf/util.py, compliance_checker/tests/test_cf.py, pyproject.toml
Merges develop into main, especially fixing import of `pyproject.toml` to include CF 1.9 checker.
=> Merge in develop

compliance_checker/cf/cf_1_9.py, compliance_checker/tests/test_cf.py
Implementation of 5.8 Domain Variables when checking against cell measures, conformance required 4/4 in CF 1.9 standard.
=> Implement checking of domain variables against cell_measures

.pre-commit-config.yaml, compliance_checker/cf/cf_1_6.py, compliance_checker/cf/cf_1_9.py, compliance_checker/protocols/zarr.py, compliance_checker/suite.py, compliance_checker/tests/test_cf.py, compliance_checker/tests/test_cli.py
This should fix the detection of nczarr on Windows but will work only on CIs with bash and conda. I guess that is our default environment for developing on Windows anyway. I'm looking into upstream a non-bash script to libnetcdf so we can drop these workarounds.
Closes https://github.com/ioos/compliance-checker/pull/1102
=> Fix windows tests

compliance_checker/cf/cf_1_6.py
Addresses #1107 by removing set logic and having consistent sort order.
=> Remove set check for certain variable attributes due to sorting issues

.github/workflows/cc-plugin-glider-test.yml, .github/workflows/cc-plugin-ncei-test.yml, .github/workflows/cc-plugin-og-test.yml, .github/workflows/cc-plugin-sgrid-test.yml, .github/workflows/cc-plugin-ugrid-test.yml, .github/workflows/codecov.yml, .github/workflows/default-tests.yml, .github/workflows/deploy-docs.yml, .github/workflows/integration-tests.yml, requirements.txt, test_requirements.txt
=> Fixes micromamba v2 failures

.github/workflows/default-tests.yml, .pre-commit-config.yaml, pyproject.toml
Also dropping Python 3.8 b/c it already reached EOL.
=> Add Python 3.13 to the test matrix

compliance_checker/cf/cf_1_6.py
This function is deprecated and will be removed in future versions of `cf-units`. It is also a single line, making this change "cheaper" than the extra import, unit conversion, and method call we have now.
=> .is_long_time_interval() is deprecated and will be removed

.pre-commit-config.yaml, compliance_checker/tests/test_ioos_sos.py, test_requirements.txt
httpretty seems to be abandoned and some of its deprecation warnings will make it unsuable soon. See https://github.com/gabrielfalcao/HTTPretty/issues/482
I'm replace it with mocket, which seems to have a 1-1 correspondence and seems to be well maintained.
=> Replace httpretty

.github/workflows/default-tests.yml, compliance_checker/cf/util.py, compliance_checker/cfutil.py, compliance_checker/suite.py, compliance_checker/tests/conftest.py, compliance_checker/tests/resources.py, compliance_checker/tests/test_suite.py, pyproject.toml, requirements.txt
Python 3.8 reached EOL and while 3.9 will only reach EOL 2025-10, pyudunits2 is py310 only and we should move away from the compiled udunits2 extension.
@benjwadams let me know what you think. Once this one is merged I'm also planning on activating pyupgrade and ruff format and slowly update the code here.
=> Minimum Python support 3.10

test_requirements.txt
Some here are run by the pre-commits or GitHub Actions. We don't need to install them everywhere.
=> Reduce the development requirements

compliance_checker/cf/util.py, compliance_checker/runner.py
Allows for group traversal described in https://github.com/ioos/compliance-checker/issues/945
Awaiting clarification on https://github.com/orgs/cf-convention/discussions/351 for lateral search.
=> Group search

compliance_checker/cf/util.py, compliance_checker/runner.py
This fixes issue #1132 
Returns None if no attributes found
Please review @benjwadams
=> FIX: Error in util.py when no attributes found in StandardNameTable

.pre-commit-config.yaml, pyproject.toml
We found `ResourceWarning: unclosed database` in Python 3.13 and `ResourceWarning: unclosed file` on Windows. These are not a high fix priority b/c they are related to the tests mocked netCDF and do not affect compliance-checker per se.
=> Filter specific warnings to find hidden bugs

compliance_checker/cf/cf_1_6.py, compliance_checker/cf/cf_1_8.py, compliance_checker/cf/cf_1_9.py, compliance_checker/cf/util.py, compliance_checker/cfutil.py, compliance_checker/tests/test_cf.py, compliance_checker/tests/test_feature_detection.py
WIP branch for handling domain variables with ragged array representations as described in #951
=> WIP Domain variables cell measures coordinates

compliance_checker/acdd.py
Adds a check for either "up" or "down" on the attribute "geospatial_vertical_positive" for the ACDD checker.
=> Add geospatial_vertical_positive value check for ACDD

compliance_checker/runner.py
This is just a tiny bugfix. It seems that `json_new` format does not write outputs of multiple tests (the initial dict is always overwritten).
=> fix report of multiple tests for `json_new` format

compliance_checker/cf/cf_1_6.py, compliance_checker/tests/test_cf.py
We have data where `nan` is used as the FillValue and is marked as an error by the compliance checker.
=> Make NaN a valid FillValue

compliance_checker/cf/cf_1_6.py, compliance_checker/tests/test_cf.py
One of our users provided data which use strings instead of arrays as the datatype for flag values. This caused a crash of the compliance-checker. This PR aims to avoid the crash.
```
byte A4O_flag_bright(lat, lon) ; 
A4O_flag_bright:flag_meanings = "A4O_flag_bright" ; 
A4O_flag_bright:flag_values = "0U 1U" ; 
A4O_flag_bright:flag_masks = "1U" ; 
A4O_flag_bright:long_name = "Level_2 bright mask for TOA reflectance (at 490) > 0.3, that includes possible clouds and sea ice" ; 
```
=> 3.5: Added additional check against wrong flag_value-types

cchecker.py
Rather insignificant bugfix: I accidentally let the compliance-checker run with `-c` without setting an actual criteria-level, which resulted in a crash with a rather ugly exception instead of pointing out the actual usage.
I am not sure whether there is some reasoning I don't understand, but having `nargs="?"` set for `criteria` results in `criteria=None`, ignoring the default, when starting the compliance checker like I did. I couldn't find any good reason why `nargs="?"` should be used here, so I removed it.
=> remove nargs for criteria in argparse

.pre-commit-config.yaml, compliance_checker/cf/cf_1_6.py
Closes #1211
@benjwadams do you mind taking a look at this one? While it passes all the tests, dealing with dates is always quite complex and error prone.
@mphemming thanks for the detailed issue in #1211. Can you test this branch against your data and see if it helps?
xref.: https://github.com/Unidata/cftime/issues/365
=> Avoid comparing cftime objects due to poor performace

.github/workflows/update-cf-names-table.yml
@benjwadams this will avoid this GitHub Action issuing table update PRs for the forks.
=> Do not run this GHA on forks

.pre-commit-config.yaml, compliance_checker/tests/test_cli.py
Netcdf-c was built with zarr and zarr-zip support, the tests passed, but it is not working here. No idea :-/
I'll file an issue upstream and update things here accordingly. For now, let's skip this test, this is feature is not really used.
=> Skip zip zarr
