ioos/compliance-checker

- README.md
Updates #65 to address an issue discovered by @abirger.
> Fix typo/line order in conda commands in README.md

- cchecker.py
> Adds exit code

- compliance_checker/cf/cf.py
> fix incorrect attribute name in check_data_types (cf.py)

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
check_independent_axis_dimensions.
The check has been changed to check:
1) whether variable dimension is a space-time dimension
2) whether variable dimension has associated coordinated variable.
Issue 72
> space-time none coordinate variable should not be checked in

- compliance_checker/acdd.py
- compliance_checker/cf/util.py
- requirements.txt
Reverts ioos/compliance-checker#110
> Revert "Using cf_units instead of udunitspy."

- compliance_checker/cf/cf.py
> Skip cf_role attr'd vars in check_units, fixes #131

- compliance_checker/acdd.py
> Fix bug in ACDD time_extents from cf_units switch

- MANIFEST.in
- README.md
- cchecker.py
- compliance_checker/data/templates/ccheck.html.j2
- compliance_checker/runner.py
- compliance_checker/suite.py
- requirements.txt
- setup.py
- Added two new command line arguments:
- `-o --output` 
- `-f --format` 
Note: I haven't implemented the REST of the functionality for the output, in other words, you can't use -o anywhere other than for HTML output.
> Adds support for outputting HTML

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
This is the branch against issue 128.
> Reimplemented the logic in check_packed_data, fixes #128

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
* add reasoning messages to check_calendar
* skip valid_calendar check if attribute missing
> Add reasoning messages to check_calendar (Fixes #153)

- compliance_checker/cf/cf.py
re-write, should I add test for all cell_method cases?
> fix cell_methods check, issue #155

- cchecker.py
- compliance_checker/runner.py
* Exceptions reported to stderr;
* Exceptions also reported for html and json output options, not just text;
* If any exceptions, cchecker.py exit value is 2, even if all successfully run checks passed.
> Fixes #163: Exception handling

- compliance_checker/cf/cf.py
- compliance_checker/runner.py
- compliance_checker/suite.py
- Adds UTF-8 support for results
- Adds more detailed result names to CF checker
- Adds limit support for JSON and HTML output
> Adds more detailed result names to CF

- compliance_checker/suite.py
- compliance_checker/tests/test_suite.py
* add unittest to test for the issue
* add clause to handle case when result name is an empty list or tuple
> Fixes #183

- requirements.txt
> Free cf_units version

- compliance_checker/cf/cf.py
> Adds better description for the 9.1 checking

- compliance_checker/cf/cf.py
There were a few lingering messages that get kept even though the checks
passed.
Fixes https://github.com/ioos/compliance-checker/issues/206
> Fixes misleading messages for valid checks

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
This plus #208 will ensure that 
http://geoport-dev.whoi.edu/thredds/dodsC/usgs/data2/emontgomery/stellwagen/CF-1.6/CAPE_COD_BAY/3051B-A.cdf
gets a perfect score.
> Doesn't require units attr for metadata vars like platform

- compliance_checker/acdd.py
Adds in logic to check for dimensions and units.  Error messages designed to catch if units exist, but no dimensions and if dimensions exist, but no units.  
I could not run the test because i do not have the file.
> Fixes #151

- README.md
- doc/ubuntu-install-guide.md
Leaves references to udunits, as it should. 
@lukecampbell @daf
> Closes #120 . For real this time.  Remove udunitspy words

- README.md
Updates the README with required C libraries for the project.
Addresses #227.
> Update README with C library dependencies

- compliance_checker/base.py
@kwilcox !d causing me problems, think you were after !s or !r in the format conversion
> str format conversion

- .travis.yml
- compliance_checker/acdd.py
- compliance_checker/base.py
- compliance_checker/cf/cf.py
- compliance_checker/ioos.py
- compliance_checker/suite.py
- compliance_checker/tests/test_cli.py
Fixes mainly Unicode related encoding issues with Python 2 which affected output of compliance checker results.  Fixes #256.
> Fix encoding issues with Python 2

- compliance_checker/suite.py
Sorts stdout results so that results now go to the proper categories
according to the priority of the tests.  Fixes #250.
> Sorts stdout results for output

- compliance_checker/suite.py
- compliance_checker/tests/test_cli.py
> Fixes 255 - JSON issues

- compliance_checker/suite.py
Attempts to fully follow redirects prior to opening a dataset, avoiding
erroneous errors on valid URLs.  Also refactors some code in `suite.py`.
Fixes #263.
> Follows redirects before looking at status code, refactors code

- .travis.yml
This PR updates the channel used to install compliance-checker dependencies.
> Change ioos to conda-forge

- cchecker.py
- Attempting to select one or more tests would yield a tuple append
error.
> Fixes default behavior for test selection

- setup.py
- tox.ini
> Fixes python3 setup errors

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
@lukecampbell actually removes it
> remove alternative coords test

- README.md
> Install instructions update

- compliance_checker/cf/cf.py
@lukecampbell 
This addresses https://github.com/ioos/compliance-checker/issues/299
> Print info about which standard name table was used

- compliance_checker/suite.py
Fixes encoding issues when attempting to pass a file when using Python
3.  Fixes #308.
> Fix encoding issues on Python3 when passing file

- .travis.yml
- compliance_checker/base.py
- compliance_checker/ioos.py
- compliance_checker/runner.py
- compliance_checker/suite.py
- compliance_checker/tests/data/http_mocks/ncsos_describesensor.xml
- compliance_checker/tests/data/http_mocks/ncsos_getcapabilities.xml
- compliance_checker/tests/test_ioos.py
- test_requirements.txt
Fixes the IOOS check suite for SOS DescribeSensor and GetCapabilities formats.  Also adds simple tests to invoke the checkers and see that they run.   Fixes an outstanding encoding issues with `process_doc` function.  Implements #216.
> Fix IOOS check suite

- README.md
- cchecker.py
- compliance_checker/runner.py
- compliance_checker/suite.py
- compliance_checker/tests/test_suite.py
Allows skipping of check methods (methods beginning with `check_`) via a
CLI flag of `-s` or `--skip-checks`. Addresses #202.
> Adds ability to skip checks

- compliance_checker/data/cf-standard-name-table.xml
@lukecampbell latest standard names table
> Bump standard name table to v36

- compliance_checker/suite.py
Does it make sense to pass this point without any checker?
> BUGFIX #306 Fail earlier if haven't loaded any checker.

- compliance_checker/cf/cf.py
This pull request is part of a larger refactor where this is me pulling on a thread and seeing what unravels.
> CF Refactor - Fixes check_coordinates_and_metadata

- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- This is part of an effort to consolidate return types and mistaken
assumptions in the code about types.
> Refactors _find_coord_vars

- compliance_checker/cfutil.py
- compliance_checker/tests/data/rotated_pole_grid.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_feature_detection.py
- adds get_axis_variables
- changes get_crs_variable to get_grid_mapping_variables
- adds new sample rotated_pole_grid.cdl
- unit tests for grid mapping detection
> Adds methods for detecting axes and grid mapping

- compliance_checker/base.py
- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/tests/data/bad_reference.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
- Refactors check_flags
- Refactors check_ancillary_variables
- Fixes python 2 unicode bug with `__repr__`
> Refactors ancillary and flag checks

- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/tests/data/chap2.cdl
- compliance_checker/tests/data/coordinate_types.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
- CF allows for coordinate types to be things besides time,lat,lon etc.
(See §4.5 Discrete Axis for more info)
- Most of Chapter 4's intro is recommended and optional
- The only required aspect is that axis be T, X, Y, or Z
- Coordinate types that are dimensionless are LOOSELY considered
coordinate variables that have a dimension size of 1.
> Refactors chapter 4 coordinate types checking

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
- Changes the priority for latitude checks
- Splits it into four checks per variable
- Adds support for rotated-pole-grid checking
> Updates latitude check

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
- Adds support for rotated grid
- Changes priorities for checks
> Updates check_longitude

- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/tests/data/vertical_coords.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_feature_detection.py
- Deprecated methods replaced by contents of cfutil.py
- Adds function to check for vertical coordinates correctly as dictated by CF §4.3.1
> Removes deprecated functions and adds identification for vertical coordinates

- compliance_checker/cfutil.py
- compliance_checker/tests/test_feature_detection.py
Fixes https://github.com/ioos/compliance-checker/issues/379
> Adds feature detection for reduced grids

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/multi-dim-coordinates.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
> Adds check for multi-dimensional coordinates

- compliance_checker/cf/cf.py
> Returns boolean for `_find_cf_standard_name_table`

- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/tests/data/2d-static-grid.cdl
- compliance_checker/tests/data/3d-static-grid.cdl
- compliance_checker/tests/data/non-comp/bad2dim.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
- compliance_checker/tests/test_feature_detection.py
- Adds feature detection for grids that don't vary with time.
- Refactors the grid checks for coordinates to use more consistent checking
- Ensure that for every grid feature defined, it is associated with true lat and true lon
> Refactors the coordinate checks for grids

- compliance_checker/cf/cf.py
Refactors util imports to use namespaced imports.  Implements #364
> Refactor util imports in cf.py

- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/tests/data/illegal-vertical.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
> Refactored checks for vertical coordinates

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/non-comp/bad.cdl
- compliance_checker/tests/test_cf.py
> Fixes calendar check

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/illegal-aux-coords.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
> Adds check for auxiliary coordinate dimensions

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
> Refactors 5.3 reduced grid checks

- compliance_checker/cf/cf.py
> Adds variable name to dimensionless vertical coord check

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/bad-instance.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
> Adds check for instance variables being refd as coords

- compliance_checker/cf/cf.py
- Iterates over only coordinate variables defining time
Fixes #370
> Fixes check_time_coordinates

- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/tests/data/appendix_h/point.cdl
- compliance_checker/tests/data/appendix_h/timeseries-incomplete.cdl
- compliance_checker/tests/data/appendix_h/timeseries-orthogonal.cdl
- compliance_checker/tests/test_cf.py
This also fixes the parsing of dimension order to allow for unlimited dimensions to precede other dimensions according to §9.3 p2
And fixes bug with duplicate vertical axes showing up in axis check.
> Start to add the Appendix H examples

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
- If units is not defined don't bother checking if it's valid UDUnits or
a string
> Fixes units checks

- compliance_checker/runner.py
This adds a better message when a checker is not installed
https://github.com/conda-forge/cc-plugin-ncei-feedstock/pull/5
> Adds MUCH better error if checker is missing or not installed

- compliance_checker/tests/data/appendix_h/timeseries-non-static.cdl
- compliance_checker/tests/data/appendix_h/timeseries-single.cdl
By the way, these both score perfect scores.
> Adds timeseries examples

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/non-comp/1d_bound_bad.cdl
- compliance_checker/tests/data/non-comp/bounds_bad_num_coords.cdl
- compliance_checker/tests/data/non-comp/bounds_bad_order.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
Handles the bounds attribute used in cell calculations.  Implements #349.
> Handles bounds attributes

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
Adds proper handling for climatology variables in section 7.4.
> Adds handling for climatology statistics

- compliance_checker/cf/cf.py
Fixes a bug where check_climatological_statistics would return None in
some instances instead of a test result.
> Fixes climatology return paths

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/examples/cf_example_cell_measures.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
Refactors cell_measure checks (§7.2).  Part of #418.
> Refactors cell_measure checks

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/cf_example_cell_measures.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
Simplifies cell bounds checks to reduce number of checks and prefer a
simplex check instead.  Part of #418.
> Simplifies cell bounds checks

- README.md
- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
- compliance_checker/tests/test_cf_integration.py
- Updates README
- Refactors the check_cell_methods to a much simpler check
- Adds unit tests for check_cell_methods
> Refactors check_cell_methods

- compliance_checker/suite.py
> Enable ESGF Authentication scheme for compliance checker

- README.md
Fixes https://github.com/ioos/compliance-checker/issues/466
> Updates readme with correct link

- README.md
Fixes https://github.com/ioos/compliance-checker/issues/454
> Updates usage guidance on README

- compliance_checker/ioos.py
Fixes https://github.com/ioos/compliance-checker/issues/465
> Changes IOOS check to ACDD spelling for acknowledgement

- compliance_checker/tests/test_util.py
- compliance_checker/util.py
Fixes https://github.com/ioos/compliance-checker/issues/462
> Fixes date checking in ACDD

- appveyor.yml
- conda.recipe/meta.yaml
- requirements.txt
> relax requirements

- compliance_checker/cf/cf.py
- compliance_checker/tests/data/bad_cell_measure1.cdl
- compliance_checker/tests/data/bad_cell_measure2.cdl
- compliance_checker/tests/data/cell_measure.cdl
- compliance_checker/tests/resources.py
- compliance_checker/tests/test_cf.py
Fixes https://github.com/ioos/compliance-checker/issues/495
This pull-request fixes the issues brought up in #495 and also adds _proper_ unit tests that actually test the check.
> Fixes cell_measures checker bug

- compliance_checker/cf/cf.py
- compliance_checker/runner.py
- compliance_checker/tests/helpers.py
- compliance_checker/tests/test_cf.py
- conda.recipe/meta.yaml
- requirements.txt
Adds fixes for cell methods requested for #509.  Additional test coverage.
> Cell methods

- compliance_checker/cf/cf.py
- compliance_checker/tests/helpers.py
- compliance_checker/tests/test_cf.py
Fix for #508 , which caused errors on certain rotated lon/lat variables.
> Grid lat lon check fixes

- compliance_checker/acdd.py
- compliance_checker/tests/test_acdd.py
- requirements.txt
Fixes issues with time extent determination for non-UTC timezones in #455.
> Time extents fix

- README.md
> Update README to be more geared towards users, not developers

- README.md
> Add Bob as a contributor

- compliance_checker/data/cf-standard-name-table.xml
Standard name table v49 came out on Feb 13
> Update with new standard name table

- compliance_checker/base.py
- compliance_checker/data/cf-standard-name-table.xml
- compliance_checker/runner.py
- compliance_checker/suite.py
- conda.recipe/meta.yaml
- requirements.txt
> Score overhaul table rebase

- compliance_checker/data/templates/ccheck.html.j2
- compliance_checker/runner.py
- compliance_checker/suite.py
- compliance_checker/tests/test_suite.py
> Added unique terminology to scoring headers for each test

- compliance_checker/suite.py
@benjwadams @daltonkell 
Compliance checker lets you pass in check names such as ```acdd``` or ```acdd:latest``` and the output passes these name through as well, making it impossible to know which version of ACDD was actually used. This puts the version number into the output so its very clear which version was used.
Also, small updates to the priority header function
> Add the check version number in all output

- appveyor.yml
Addresses https://github.com/ioos/compliance-checker/pull/555#issuecomment-372460190
> Workaround  miniconda update

- compliance_checker/base.py
> Add warning about score groups

- README.md
- cchecker.py
- compliance_checker/data/templates/ccheck_wrapper.html.j2
- compliance_checker/runner.py
- compliance_checker/suite.py
Addresses https://github.com/ioos/compliance-checker/issues/553
> Update README, cleanup standard output

- cchecker.py
- compliance_checker/runner.py
@benjwadams please review
Addresses https://github.com/ioos/compliance-checker/issues/313
> Output several formats in 1 run

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
@benjwadams @mhidas 
Fixes https://github.com/ioos/compliance-checker/issues/461
> CF featureType case insensitive

- compliance_checker/protocols/opendap.py
@cehbrecht I added your patch. 
Fixes https://github.com/ioos/compliance-checker/issues/539
> Enable ESGF Authentication scheme

- compliance_checker/_version.py
@ocefpaf this was the piece I needed to update after switching the prefix in setup.cfg
> Update prefix in _version.py

- compliance_checker/base.py
- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/tests/helpers.py
- compliance_checker/tests/test_cf.py
- compliance_checker/tests/test_suite.py
Fixes a number of issues related to non-string units and standard_name attributes in variables.  Addresses #542
> Valid string units and standard name

- .gitignore
- .travis.yml
- compliance_checker/__init__.py
- compliance_checker/base.py
- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/suite.py
- compliance_checker/tests/test_cf_integration.py
- conda-requirements.txt
- conda-requirements_pre3_2.txt
- conda.recipe/meta.yaml
- requirements.txt
- Improves test speed by using LRU cache from `functools` (`functools32` is used for python2.7 tests)
- Implements unicode encoding for the section characters
The goal of this PR is twofold: 
a) Show the time improvements between the tests 
b) Test if the unicode escapes fix the TravisCI builds from my last PR (#599)
Shout out to @jakepolatty for the great work
> Performance test

- compliance_checker/__init__.py
- compliance_checker/runner.py
Fixes error messages when deallocating MemoizedDataset
> Dealloc ds error fix

- compliance_checker/suite.py
- requirements.txt
> Eliminates tabular standard output

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
Changes the regex used to validate the climatology cell_methods to one
slightly shorter, and hopefully more efficient.  Also adds test
coverage for various valid and invalid climatology cell_methods
attributes.
> Changes regex, adds climatology cell_methods tests

- .travis.yml
- requirements.txt
If I understand the tests correctly the segfault occurs when this line is called:
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/suite.py#L478
I'm not sure if the issue is with `tabulate` or the inputs we are feeding for the table.
> Test with Python 3.7

- compliance_checker/cf/cf.py
Additionally, makes some regex strings with invalid escape sequences valid by making the string a raw string
> Re-tool the climatology check for clarity and efficiency

- compliance_checker/runner.py
Handles the return status of multiple check suites, returning non-zero
if any of the check suites did not pass and/or if unhandled
compliance-checker errors.  Possible fix for #534.
> Handle return value from multiple check suites

- compliance_checker/cf/cf.py
Relaxes type checking on attributes.
For string attributes, check that the parent attribute is a string
"kind", i.e. data.kind returns "S"
For other data types, check that the .dtype.type matches between attribute
and parent.  This eliminates issues with endianness checking.
Also modifies/abridges valid_{min,max,range}, and _FillValue type
checking code to follow the above.
> Relax strictness on data type checking

- compliance_checker/acdd.py
- compliance_checker/base.py
- compliance_checker/tests/test_base.py
- compliance_checker/util.py
Alters priority of tests relating to ISO date global attributes in ACDD 1.3.
Refactors handling of global attribute lists to use an `OrderedDict` for the underlying operations.
Addresses #519
> ACDD refactor date

- compliance_checker/runner.py
- compliance_checker/tests/test_cli.py
Fixes an issue when multiple test suites were selected where only the
last result was returned.  Adds unit test to verify checks are working
as intended.
> Fixes multi checker return status

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
> Handle non-string standard_name_vocubulary global attribute

- .appveyor.yml
This should get the environment building again.
> Fix and modernize AppVeyor

- compliance_checker/cf/__init__.py
- compliance_checker/cf/appendix_e.py
- compliance_checker/cf/appendix_f.py
- compliance_checker/cf/cf.py
- compliance_checker/ioos.py
- compliance_checker/suite.py
- compliance_checker/tests/test_cf.py
- setup.py
Un-squashed the previous monolithic commits made for CF 1.7 into a series of modular commits, each adding a feature.
> Cf 1 7 multicommit

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
Implements checking for `crs_wkt` grid mapping attribute under CF 1.7 checker.
> `crs_wkt` implementation

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
in test/test_cf.py, function test_longitude:
* replaced `4.1 Latitude Coordinates` by `4.2 Longitude Coordinate`
in test/test_cf.py, function test_latitude:
* replaced `4.1 Latitude Coordinates` by `4.1 Latitude Coordinate`
in cf/cf.pyL
* replaced `4.1 Latitude Coordinates` by `4.1 Latitude Coordinate`
* replaced `4.2 Longitude Coordinates` by `4.2 Longitude Coordinate`
* in `check_longitude` replaced `'4.1'` by `'4.2'`
> fixed "4.2 Longitude Coordinate" and minor related; fixed #676

- .appveyor.yml
- .travis.yml
- requirements.txt
> Test on Python 3.8

- .appveyor.yml
- .travis.yml
- compliance_checker/cf/cf.py
- gen_conda_requirements.py
- requirements.txt
Merges in master to bring latest changes to cf_1_7_dev_rebase
> Cf 1 7 dev rebase master merge

- .appveyor.yml
- gen_conda_requirements.py
- requirements.txt
Should help with https://github.com/ioos/compliance-checker/issues/705#issuecomment-558338809
> Investigate env failures appveyor

- compliance_checker/base.py
- compliance_checker/ioos.py
- compliance_checker/tests/test_base.py
Allows splitting of components.
Adds CSV check for contributor_url.
Changes interface for `attr_check` to only allow
> Splitter validate

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Checks that naming_authority is either a URL or a reversed DNS string.
> Adds validation for naming_authority

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Adds checks for creator_type and publisher_type global attributes,
de-facto defaulting to a value of "person" if the attribute does not
exist.
> Adds checks for creator_type and publisher_type

- README.md
This commit updates the contributor email details in the README.
> Updates contributor details in README

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Addresses https://github.com/ioos/compliance-checker/pull/752#issuecomment-593609604
> Change GEOIDE to NOAA-NCEI

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
> WIP Separate the gts_ingest global and variable checks

- compliance_checker/ioos.py
> Improve qartod_variables:references message

- README.md
Add ERDDAP documentation. Addresses #637 and #723.
> Add ERDDAP documentation to README

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Only use messages if the check fails.
> Ioos convert to conditional results

- compliance_checker/base.py
- compliance_checker/tests/test_base.py
- compliance_checker/tests/test_ioos_profile.py
Makes the return type of validate_type (bool, [str]) making the return
type consistent with the validate function.
> Returns validate_type messages as list of str

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Separate platform checks from the CF DSG checks and add corresponding unit tests, per #748.
> IOOS  1.2  platform  DSG

- compliance_checker/ioos.py
Add "NDBC" to the GTS Ingest check messages. Addresses https://github.com/ioos/compliance-checker/issues/759#issuecomment-621829580
> Add NDBC string to GTS Ingest check messages

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Always "fail" the GTS ingest check so that users are informed of
which variables have qualified versus which ones have not.
Adjust unit tests accordingly.
Addresses #759 (most recent comments)
> NDBC and GTS Ingest alterations

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Addresses most recent comments in #748.
> Update platform cf_role messages

- compliance_checker/acdd.py
- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
- compliance_checker/ioos.py
- compliance_checker/runner.py
- compliance_checker/suite.py
- compliance_checker/tests/test_acdd.py
- compliance_checker/tests/test_cf.py
Pretty much what the title says.
> got bored and decided to run codespell on the code

- compliance_checker/base.py
- compliance_checker/suite.py
Implement finalizer to ensure no side effects persist to the
LRU cache shared by multiple checker instances.
A last-recently-used (LRU) cache is used to improve memory use and decrease run time of the checker by caching certain function calls. This cache is shared between objects during the interpreter lifecycle. In issue #826, side-effects of an ACDD function caused the cache to mutate and store variables in it which should not have existed. These variables were then used during the next check (CF), which caused errors. New behavior shows that the cache is no longer shared and the tests behave as expected:
```
(env38) dalton@ubuntu:~/compliance-checker$ python issue_826.py                                                                    
Using cached standard name table v66 from …
```
> Address issue #826 and remove side effects to the LRU cache

- compliance_checker/cf/cf.py
@neumannd put in a great PR in #835; this tweaks it ever so slightly to use a more idiomatic `numpy` expression per review of @benjwadams
> Small addition to neumannd drop zero dim vars for feature type search

- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Addresses #819 and removes checks for "geospatial" variables
> Remove "geospatial" variable checks

- .github/workflows/miniconda-win.yml
Using a more robust GH Action for conda.
> fix GitHub Actions on Windows

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- compliance_checker/ioos.py
- compliance_checker/tests/test_ioos_profile.py
Update to the latest version and syntax of the GitHub Action.
> fix pre-commit GHA

- compliance_checker/cf/cf.py
- compliance_checker/suite.py
- compliance_checker/tests/test_cf_integration.py
Hopefully fixes outstanding integration test errors.
> Integration test fixes

- compliance_checker/cf/cf.py
Just picking off the smallest github issues:
https://github.com/ioos/compliance-checker/issues/718
https://github.com/ioos/compliance-checker/issues/717
https://github.com/ioos/compliance-checker/issues/785
Updating the wording in the messages didn't break any of the tests that check against hardcoded messages.
> Little issues

- .github/ISSUE_TEMPLATE/compliance-checker-issue-report.md
- .github/workflows/publish.yml
- .pre-commit-config.yaml
- compliance_checker/cf/cf.py
- compliance_checker/cfutil.py
@mwengren this is the first one on my list. When we get the PyPI credentials sorted out this will become a boilerplate PR to the repos we care about publishing.
@benjwadams can you add my and/or @mwengren as a PyPI maintainer so we can generate the token to make this work?
> add PyPI auto-publish

- .github/workflows/default-tests.yml
I also removed the py36 b/c it reached its end of life.
> test on py3k

- .pre-commit-config.yaml
Found:
```
compliance_checker/cf/cf_18.py:661:21: F821 undefined name 'ds'
compliance_checker/cf/cf_18.py:661:42: F821 undefined name 'ds'
compliance_checker/cf/cf_18.py:665:33: F821 undefined name 'ds'
compliance_checker/cf/cf_18.py:666:27: F821 undefined name 'ds'
compliance_checker/ioos.py:959:20: F821 undefined name 'good_result'
compliance_checker/cf/cf.py:4102:25: F821 undefined name 'boundary_variable'
```
> Re enable flake8

- compliance_checker/cf/cf.py
- compliance_checker/tests/test_cf.py
Probable fix to #842
cc @mhidas
> Fix undefined function in scale_factor/add_offset, typo

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
Fixes improper comparison short/int variable against floating point
scale_factor/add_offset.
> Fix scale_factor/add_offset with short/int var

- compliance_checker/suite.py
- compliance_checker/tests/test_suite.py
Closes #907
Working on tests...
> use pathlib

- compliance_checker/cf/appendix_c.py
- compliance_checker/cf/cf_1_6.py
- compliance_checker/cf/cf_1_7.py
- compliance_checker/cf/util.py
- compliance_checker/cfutil.py
- compliance_checker/tests/test_cf.py
Fix handling of standard name modifiers, including deprecation warnings in CF >= 1.7.
> Standard name units and modifiers

- compliance_checker/tests/test_protocols.py
Fixes protocol test failures mentioned in #904.
> Fix protocol tests that had broken URLs

- compliance_checker/cf/appendix_d.py
- compliance_checker/cf/cf_1_6.py
- compliance_checker/cfutil.py
- compliance_checker/tests/test_cf_integration.py
Fixes issues in integration tests.
Other issues addressed
- Remove bounds from consideration of geophysical variables
- Add in associated standard names for computed standard names used in formula_terms.
> Fix integration tests rebase

- compliance_checker/cf/cf_1_6.py
- compliance_checker/cf/util.py
- compliance_checker/tests/test_cf.py
Adds comments for sections and tests corresponding to CF Conformance documents
> Improve conformance

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
Handles nonstandard calendars which need to define leap time definitions.
> Handle nonstandard calendar and leap time in time variables

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/helpers.py
- compliance_checker/tests/test_cf.py
- compliance_checker/tests/test_ioos_profile.py
Suggests nearby corrections for incorrect standard names.  Implements #806.
> Standard name recommendations

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
Implements missing point of #960 1/2 .
> Only allow fixed length string variables to be one or two-dimensional

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
> Leilabbb cf1 9 2 5 1check missing data valid and actual range of data

- compliance_checker/cf/appendix_d.py
- compliance_checker/tests/test_cf.py
> Ocean sigma z coordinate appendix d

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
> Calendar fixes conformance

- compliance_checker/cf/cf_1_7.py
- compliance_checker/tests/test_cf.py
> 7.1 cell boundaries

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
> Fix units check for status_flag variables

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
@mhidas, addresses #971 -- tested with file submitted in the linked issue.
> Make calendar check case insensitive

- compliance_checker/cf/util.py
> update standard names URL

- compliance_checker/cf/cf_1_6.py
added a test to verify units are recognized by UDUNITS in the check_cell_measures() function
> Update check_cell_measures() function in cf_1_6.y

- .pre-commit-config.yaml
- compliance_checker/cf/cf_1_6.py
- compliance_checker/cf/cf_1_8.py
- compliance_checker/tests/test_cf.py
I also run pre-commit on the files I touched so we slowly get them all back into compliance.
> Fix numpy deprecations that are errors in 1.24.2

- .github/workflows/cc-checker-ugrid-test.yml
- .github/workflows/cc-plugin-glider-test.yml
- .github/workflows/cc-plugin-sgrid-test.yml
- .github/workflows/cc-plugin-ugrid-test.yml
- .github/workflows/codecov.yml
- .github/workflows/default-tests.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pypi.yml
@benjwadams the master/develop dance erased some changes or just brought to light some inconsistencies. This should get us up to speed with regards to GitHub Actions testing.
> fix minor inconsistencies in GHA

- compliance_checker/cf/cf_1_6.py
- compliance_checker/cf/cf_1_7.py
- compliance_checker/cf/cf_1_9.py
- compliance_checker/tests/test_cf.py
> Refactor cell_measures, properly handling quantity squared/cubed

- compliance_checker/cf/cf_1_7.py
- compliance_checker/cf/cf_base.py
- compliance_checker/tests/test_cf.py
Implements remaining points of #946
> Formula terms revamp

- test_requirements.txt
See https://github.com/kevin1024/vcrpy/issues/688
> workaround latest urllib3

- compliance_checker/cf/cf_1_6.py
File path was not properly displayed
> Fix filepath bug

- .github/workflows/cc-plugin-og-test.yml
@jr3cermak this is only to ensure that future PRs to compliance-checker won't break the plugin.
> add cc-plugin-og plugin test

- .github/workflows/default-tests.yml
> We no longer need this part.

- compliance_checker/cf/util.py
@benjwadams this is the code line from https://github.com/ioos/compliance-checker/pull/1118#discussion_r1831860028
Let's see of that one is covered by our tests.
> is this covered by the tests?

- compliance_checker/cfutil.py
> Remove unused argument

- compliance_checker/cf/cf_1_7.py
- compliance_checker/cf/cf_1_8.py
- compliance_checker/cf/cf_1_9.py
- compliance_checker/cf/util.py
- compliance_checker/cfutil.py
- compliance_checker/tests/helpers.py
- compliance_checker/tests/test_cf.py
- compliance_checker/tests/test_cf_integration.py
- compliance_checker/tests/test_feature_detection.py
> Exclude projected x/y from treatment as lon/lat

- pyproject.toml
> Suppress some known harmless warnings

- compliance_checker/cf/cf_1_6.py
- compliance_checker/tests/test_cf.py
> Fix two argument form of climatology cell_methods

- README.md
- docs/cf_feature_parity_matrix.md
Adds a table with current Compliance Checker support for the various sections of the CF Conventions.
> Adds feature CF feature parity matrix

- compliance_checker/tests/test_ioos_sos.py
- test_requirements.txt
Latest version of `mocket` simplified the imports a bit.
> Fix mocket import

- .pre-commit-config.yaml
- compliance_checker/suite.py
Working on #1150 and I want to remove any commit not related to zizmor from it. This one should be an easy merge, just udpates.
> Update pre commits

- .github/workflows/cc-plugin-glider-test.yml
- .github/workflows/cc-plugin-ncei-test.yml
- .github/workflows/cc-plugin-og-test.yml
- .github/workflows/cc-plugin-sgrid-test.yml
- .github/workflows/cc-plugin-ugrid-test.yml
- .github/workflows/codecov.yml
- .github/workflows/default-tests.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pypi.yml
- .pre-commit-config.yaml
Add `zizmor` checks and some suggested fixes.
The PyPI one would be better addressed by setting trusted publishers. I'm looking into it.
> Lint GitHub Actions files with zizmor

- compliance_checker/tests/__init__.py
- compliance_checker/tests/test_acdd.py
- compliance_checker/tests/test_base.py
- compliance_checker/tests/test_cf.py
- compliance_checker/tests/test_feature_detection.py
- compliance_checker/tests/test_ioos_profile.py
- compliance_checker/tests/test_ioos_sos.py
- compliance_checker/tests/test_suite.py
- compliance_checker/tests/test_util.py
Initial attempt at moving over to pytest.
Fixtures and other pytest features aren't used yet, most work was done on removing old unittest idioms. Will require further refactoring for better code reuse and proper cleanup code will need to be reimplemented.
Implements #874
> Convert tests over to pytest

- .github/dependabot.yml
- .github/workflows/cc-plugin-glider-test.yml
- .github/workflows/cc-plugin-ncei-test.yml
- .github/workflows/cc-plugin-og-test.yml
- .github/workflows/cc-plugin-sgrid-test.yml
- .github/workflows/cc-plugin-ugrid-test.yml
- .github/workflows/codecov.yml
- .github/workflows/default-tests.yml
- .github/workflows/deploy-docs.yml
- .github/workflows/integration-tests.yml
- .github/workflows/pypi.yml
- .pre-commit-config.yaml
Needed in https://github.com/ioos/compliance-checker/pull/1169
> Secure hashes

- compliance_checker/cf/cf_1_6.py
- compliance_checker/cf/cf_base.py
- compliance_checker/cf/util.py
- compliance_checker/tests/test_cf.py
Related to issue #949 
Listing Requirement Implementation for CF1-8 Section 5 : 
New Implementations:
1. Checks that the `coordinates` attribute is a space-separated list of valid variable names, and all listed variables exist in the dataset. Function: check_coordinates_attribute_format()
2. Checks that a coordinate variable must not have the _FillValue or missing_value attributes. Function: check_invalid_coordinate_attr()
3. Checks that spatial/temporal dimensions (time, lat, lon, height)  used in geophysical variables have proper coordinate variables. Function: check_spatiotemporal_dims_have_coordinate_vars()
Existing Implementations:
4. Satisfying CF 1.8 Chapter 5, paragraph 3: Dimensions of auxiliary coordinates must be a subset of the variable they’re attached to (with two documented …
> Implementation for CF1-8 Section 5: Coordinate Systems

- README.md
Note that the CF-1.8 and CF-1.7 files were created in the same day. We wither lost some history or they were indeed created together.
> Update releases README

- compliance_checker/cf/cf_1_9.py
> Add int64 to variable data types (#1236)
